"""Investment research brief generator powered by Claude.

Uses claude-opus-4-8 with prompt caching on the (large, static) system prompt to
reduce latency and cost on repeated requests with the same analyst persona.
Both sync (``generate``) and async (``generate_async``) entry points are
provided — FastAPI routes should call ``generate_async``; CLI scripts can use
``generate`` directly.

Parsing contract:
    Claude is instructed to use exactly seven ``## SECTION_NAME`` headers.
    ``_parse_response`` splits on those headers and maps each to a field on
    ``ResearchBrief``.  Missing or misspelled sections default to an empty
    string so the caller always gets a fully-populated model back.
"""

from __future__ import annotations

import asyncio
import logging
import re
import sys
from datetime import datetime, timezone
from typing import Optional

import anthropic
from pydantic import BaseModel, Field

from app.analysis.sentiment import SentimentResult
from app.config import settings
from app.models.schemas import FinancialSnapshot, SECFiling

log = logging.getLogger(__name__)

# ── Constants ─────────────────────────────────────────────────────────────────

# The user originally specified "claude-sonnet-4-20250514"; that's the now-
# deprecated snapshot ID for what is currently claude-sonnet-4-6.
# We default to claude-opus-4-8 (most capable) but expose it as a parameter
# so callers can choose based on their latency / cost requirements.
_DEFAULT_MODEL = "claude-opus-4-8"

# How many characters of filing text to include in the prompt.
# The fetcher caps at 80 K chars; we use a smaller window here to keep
# the prompt focused on the most informative sections.
_MAX_FILING_CHARS = 12_000

# Retry budget for transient API errors (RateLimitError, APIConnectionError).
_MAX_RETRIES = 2
_RETRY_DELAY_S = 5.0

# Max tokens for Claude's response — a full 7-section brief is ~2 000–3 500
# tokens; 8 192 gives comfortable headroom.
_MAX_TOKENS = 8_192

# Section headers Claude is instructed to emit, in order.
_SECTIONS = [
    "COMPANY OVERVIEW",
    "EARNINGS ANALYSIS",
    "SENTIMENT ASSESSMENT",
    "BULL CASE",
    "BEAR CASE",
    "KEY RISKS",
    "INVESTMENT OUTLOOK",
]

# The system prompt is large (~600 tokens) and identical for every request, so
# it's a perfect candidate for prompt caching.  The cache_control marker is
# placed on this block at call time (see _make_system_param).
_SYSTEM_PROMPT = """\
You are a senior equity research analyst at Goldman Sachs Investment Research \
with 20 years of experience covering technology, consumer, and industrial companies. \
Your research briefs are known for their analytical rigour, clear structure, and \
actionable investment conclusions.

When generating a research brief, follow these principles:
- Ground every assertion in the data provided; never fabricate figures.
- Distinguish between near-term catalysts and long-term structural factors.
- Present bull and bear cases with equal intellectual honesty.
- Quantify risks where possible; flag qualitative risks clearly.
- Keep each section concise and free of filler language.
- The Investment Outlook must conclude with a clear stance — Outperform, \
Neutral, or Underperform — with a one-sentence rationale and, where the data \
supports it, a 12-month price target.

Format your response using EXACTLY these seven section headers in this order, \
each prefixed with ##:

## COMPANY OVERVIEW
## EARNINGS ANALYSIS
## SENTIMENT ASSESSMENT
## BULL CASE
## BEAR CASE
## KEY RISKS
## INVESTMENT OUTLOOK

Each section should be 2–5 concise paragraphs.  Do not include any text before \
the first ## header or after the last section.
"""


# ── Result model ──────────────────────────────────────────────────────────────

class ResearchBrief(BaseModel):
    """Structured investment research brief generated by Claude.

    Each field maps to one section of the Goldman Sachs–style report.
    Empty strings indicate that Claude's response did not include that section
    (parse failure), not that the section was intentionally omitted.
    """

    ticker: str
    company_name: Optional[str] = None
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    model: str

    company_overview: str = ""
    earnings_analysis: str = ""
    sentiment_assessment: str = ""
    bull_case: str = ""
    bear_case: str = ""
    key_risks: str = ""
    investment_outlook: str = ""

    # Token usage from the API response — useful for cost monitoring.
    input_tokens: Optional[int] = None
    output_tokens: Optional[int] = None
    cache_read_tokens: Optional[int] = None
    cache_creation_tokens: Optional[int] = None


# ── Section → field name mapping ──────────────────────────────────────────────

_SECTION_FIELDS: dict[str, str] = {
    "COMPANY OVERVIEW": "company_overview",
    "EARNINGS ANALYSIS": "earnings_analysis",
    "SENTIMENT ASSESSMENT": "sentiment_assessment",
    "BULL CASE": "bull_case",
    "BEAR CASE": "bear_case",
    "KEY RISKS": "key_risks",
    "INVESTMENT OUTLOOK": "investment_outlook",
}


# ── Main class ────────────────────────────────────────────────────────────────

class BriefGenerator:
    """Generates structured investment research briefs via the Claude API.

    Both sync and async entry points are provided:
    - ``generate()``       — synchronous; suitable for scripts and tests.
    - ``generate_async()`` — async; preferred for FastAPI route handlers.

    The system prompt is sent with ``cache_control: {type: "ephemeral"}``
    so repeated calls reuse the cached prefix, reducing latency and cost.

    Example::

        generator = BriefGenerator()
        brief = generator.generate(filing, financials, sentiment)
        print(brief.investment_outlook)
    """

    def __init__(self, model: str = _DEFAULT_MODEL) -> None:
        self._model = model
        self._client = anthropic.Anthropic(api_key=settings.anthropic_api_key)
        self._async_client = anthropic.AsyncAnthropic(
            api_key=settings.anthropic_api_key
        )

    # ── Public API ────────────────────────────────────────────────────────────

    def generate(
        self,
        filing: SECFiling,
        financials: FinancialSnapshot,
        sentiment: SentimentResult,
    ) -> ResearchBrief:
        """Generate a research brief synchronously.

        Streams the response internally and returns the complete brief once
        all tokens have arrived, providing HTTP-timeout protection for long
        outputs without exposing streaming complexity to the caller.

        Args:
            filing:     SEC filing record (text_content populated by the
                        EDGAR fetcher).
            financials: Yahoo Finance snapshot for the same ticker.
            sentiment:  Pre-computed sentiment result for the filing text.

        Returns:
            A fully-populated ResearchBrief.

        Raises:
            anthropic.APIError: On unrecoverable API errors after retries.
        """
        user_prompt = self._build_user_prompt(filing, financials, sentiment)
        response = self._call_with_retry(user_prompt)
        return self._parse_response(response, filing.ticker, financials.company_name)

    async def generate_async(
        self,
        filing: SECFiling,
        financials: FinancialSnapshot,
        sentiment: SentimentResult,
    ) -> ResearchBrief:
        """Generate a research brief asynchronously.

        Identical to ``generate()`` but uses the async Anthropic client —
        preferred in FastAPI route handlers to avoid blocking the event loop.

        Args:
            filing:     SEC filing record.
            financials: Yahoo Finance snapshot.
            sentiment:  Pre-computed sentiment result.

        Returns:
            A fully-populated ResearchBrief.
        """
        user_prompt = self._build_user_prompt(filing, financials, sentiment)
        response = await self._async_call_with_retry(user_prompt)
        return self._parse_response(response, filing.ticker, financials.company_name)

    # ── Internal: API calls ───────────────────────────────────────────────────

    def _call_with_retry(self, user_prompt: str) -> anthropic.types.Message:
        """Stream a completion with exponential-backoff retry on transient errors.

        Args:
            user_prompt: The assembled user-turn message text.

        Returns:
            The final ``Message`` object after streaming completes.

        Raises:
            anthropic.APIError: After all retries are exhausted.
        """
        last_exc: Optional[Exception] = None
        for attempt in range(_MAX_RETRIES + 1):
            try:
                with self._client.messages.stream(
                    model=self._model,
                    max_tokens=_MAX_TOKENS,
                    system=self._make_system_param(),
                    messages=[{"role": "user", "content": user_prompt}],
                ) as stream:
                    return stream.get_final_message()
            except anthropic.RateLimitError as exc:
                last_exc = exc
                delay = _RETRY_DELAY_S * (2**attempt)
                log.warning(
                    "Claude rate-limited (attempt %d/%d). Retrying in %.1fs.",
                    attempt + 1,
                    _MAX_RETRIES + 1,
                    delay,
                )
                import time
                time.sleep(delay)
            except anthropic.APIConnectionError as exc:
                last_exc = exc
                delay = _RETRY_DELAY_S * (2**attempt)
                log.warning(
                    "Claude connection error (attempt %d/%d). Retrying in %.1fs: %s",
                    attempt + 1,
                    _MAX_RETRIES + 1,
                    delay,
                    exc,
                )
                import time
                time.sleep(delay)
            except anthropic.APIStatusError as exc:
                log.error(
                    "Claude API error %d: %s (request_id=%s)",
                    exc.status_code,
                    exc.message,
                    exc._request_id,
                )
                raise
        raise last_exc  # type: ignore[misc]

    async def _async_call_with_retry(
        self, user_prompt: str
    ) -> anthropic.types.Message:
        """Async version of ``_call_with_retry``.

        Args:
            user_prompt: The assembled user-turn message text.

        Returns:
            The final ``Message`` object after streaming completes.
        """
        last_exc: Optional[Exception] = None
        for attempt in range(_MAX_RETRIES + 1):
            try:
                async with self._async_client.messages.stream(
                    model=self._model,
                    max_tokens=_MAX_TOKENS,
                    system=self._make_system_param(),
                    messages=[{"role": "user", "content": user_prompt}],
                ) as stream:
                    return await stream.get_final_message()
            except anthropic.RateLimitError as exc:
                last_exc = exc
                delay = _RETRY_DELAY_S * (2**attempt)
                log.warning(
                    "Claude rate-limited (attempt %d/%d). Retrying in %.1fs.",
                    attempt + 1,
                    _MAX_RETRIES + 1,
                    delay,
                )
                await asyncio.sleep(delay)
            except anthropic.APIConnectionError as exc:
                last_exc = exc
                delay = _RETRY_DELAY_S * (2**attempt)
                log.warning(
                    "Claude connection error (attempt %d/%d). Retrying in %.1fs: %s",
                    attempt + 1,
                    _MAX_RETRIES + 1,
                    delay,
                    exc,
                )
                await asyncio.sleep(delay)
            except anthropic.APIStatusError as exc:
                log.error(
                    "Claude API error %d: %s (request_id=%s)",
                    exc.status_code,
                    exc.message,
                    exc._request_id,
                )
                raise
        raise last_exc  # type: ignore[misc]

    # ── Internal: prompt construction ─────────────────────────────────────────

    @staticmethod
    def _make_system_param() -> list[dict]:
        """Return the system parameter with cache_control on the prompt block.

        Placing ``cache_control`` here causes the Anthropic API to cache the
        system prompt prefix; subsequent calls within the 5-minute TTL pay
        ~0.1× the normal input token cost for this block.
        """
        return [
            {
                "type": "text",
                "text": _SYSTEM_PROMPT,
                "cache_control": {"type": "ephemeral"},
            }
        ]

    def _build_user_prompt(
        self,
        filing: SECFiling,
        financials: FinancialSnapshot,
        sentiment: SentimentResult,
    ) -> str:
        """Assemble the user-turn message from all three data sources.

        The prompt is structured so Claude can read financial metrics first,
        then the filing excerpt, then the quantitative sentiment score.  This
        ordering prevents the long filing text from burying the numbers.

        Args:
            filing:     SEC filing with optional text_content.
            financials: Yahoo Finance snapshot.
            sentiment:  Pre-computed sentiment analysis result.

        Returns:
            A multi-section string ready to send as the user message.
        """
        filing_excerpt = (
            (filing.text_content or "")[:_MAX_FILING_CHARS].strip()
            or "[Filing text not available]"
        )

        return f"""\
Generate an investment research brief for {filing.ticker} \
({financials.company_name or filing.ticker}) using the data below.

=== FINANCIAL SNAPSHOT ===
{self._format_financials(financials)}

=== SEC FILING METADATA ===
Form Type  : {filing.form_type}
Filed Date : {filing.filed_date}
Accession  : {filing.accession_number}

=== FILING TEXT EXCERPT (first {_MAX_FILING_CHARS:,} chars) ===
{filing_excerpt}

=== QUANTITATIVE SENTIMENT ANALYSIS ===
Score      : {sentiment.score:+.4f}  (range −1.0 to +1.0; positive = bullish)
Label      : {sentiment.label}
Confidence : {sentiment.confidence:.4f}

Use the sentiment score as supporting evidence in the SENTIMENT ASSESSMENT section. \
Follow the seven-section format from your instructions exactly.
"""

    @staticmethod
    def _format_financials(snap: FinancialSnapshot) -> str:
        """Render a FinancialSnapshot as a compact, analyst-readable table.

        Args:
            snap: Yahoo Finance snapshot to format.

        Returns:
            Multi-line string with labelled key–value pairs.
        """

        def _fmt(
            value: Optional[float],
            prefix: str = "",
            suffix: str = "",
            scale: float = 1.0,
            decimals: int = 2,
        ) -> str:
            if value is None:
                return "N/A"
            scaled = value / scale
            return f"{prefix}{scaled:,.{decimals}f}{suffix}"

        lines = [
            f"Company          : {snap.company_name or 'N/A'}",
            f"Sector           : {snap.sector or 'N/A'}",
            f"Industry         : {snap.industry or 'N/A'}",
            f"Current Price    : {_fmt(snap.current_price, '$')}",
            f"Market Cap       : {_fmt(snap.market_cap, '$', 'B', 1e9, 1)}",
            f"Revenue (TTM)    : {_fmt(snap.revenue_ttm, '$', 'B', 1e9, 1)}",
            f"Net Income (TTM) : {_fmt(snap.net_income_ttm, '$', 'B', 1e9, 1)}",
            f"EPS (TTM)        : {_fmt(snap.eps_ttm, '$')}",
            f"P/E Ratio (TTM)  : {_fmt(snap.pe_ratio, decimals=1)}x",
            f"Forward P/E      : {_fmt(snap.forward_pe, decimals=1)}x",
            f"Price/Book       : {_fmt(snap.price_to_book, decimals=2)}x",
            f"Dividend Yield   : {_fmt(snap.dividend_yield, suffix='%', scale=0.01, decimals=2)}"
            if snap.dividend_yield else "Dividend Yield   : N/A",
            f"52-Week High     : {_fmt(snap.fifty_two_week_high, '$')}",
            f"52-Week Low      : {_fmt(snap.fifty_two_week_low, '$')}",
            f"Analyst Target   : {_fmt(snap.analyst_target_price, '$')}",
            f"Consensus        : {snap.recommendation or 'N/A'}",
        ]
        return "\n".join(lines)

    # ── Internal: response parsing ────────────────────────────────────────────

    def _parse_response(
        self,
        response: anthropic.types.Message,
        ticker: str,
        company_name: Optional[str],
    ) -> ResearchBrief:
        """Extract structured sections from Claude's response text.

        Splits on ``## HEADER`` markers and maps each block to the matching
        field on ``ResearchBrief``.  Unrecognised headers are logged and
        skipped; missing expected sections default to empty strings.

        Args:
            response:     Raw ``Message`` returned by the Anthropic API.
            ticker:       Stock ticker for the brief.
            company_name: Human-readable company name (optional).

        Returns:
            Fully-populated ResearchBrief with token usage attached.
        """
        raw_text = next(
            (block.text for block in response.content if block.type == "text"), ""
        )

        # Split on "## HEADER" boundaries; the sentinel leading "\n" ensures
        # a leading ## is detected by the pattern.
        section_map: dict[str, str] = {}
        parts = re.split(r"\n##\s+", "\n" + raw_text)
        for part in parts[1:]:  # parts[0] is text before the first ## (empty)
            newline_idx = part.find("\n")
            if newline_idx == -1:
                header, content = part.strip().upper(), ""
            else:
                header = part[:newline_idx].strip().upper()
                content = part[newline_idx:].strip()
            if header in _SECTION_FIELDS:
                section_map[header] = content
            else:
                log.debug("Unrecognised section header from Claude: %r", header)

        if len(section_map) < len(_SECTIONS):
            missing = set(_SECTIONS) - set(section_map)
            log.warning(
                "Brief for %s is missing sections: %s", ticker, ", ".join(missing)
            )

        usage = response.usage
        return ResearchBrief(
            ticker=ticker.upper(),
            company_name=company_name,
            model=response.model,
            company_overview=section_map.get("COMPANY OVERVIEW", ""),
            earnings_analysis=section_map.get("EARNINGS ANALYSIS", ""),
            sentiment_assessment=section_map.get("SENTIMENT ASSESSMENT", ""),
            bull_case=section_map.get("BULL CASE", ""),
            bear_case=section_map.get("BEAR CASE", ""),
            key_risks=section_map.get("KEY RISKS", ""),
            investment_outlook=section_map.get("INVESTMENT OUTLOOK", ""),
            input_tokens=usage.input_tokens,
            output_tokens=usage.output_tokens,
            cache_read_tokens=getattr(usage, "cache_read_input_tokens", None),
            cache_creation_tokens=getattr(
                usage, "cache_creation_input_tokens", None
            ),
        )


# ── CLI smoke test ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import os
    from datetime import date

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
    )

    api_key = settings.anthropic_api_key
    if not api_key or api_key.lower() == "placeholder":
        print(
            "\nERROR: Set ANTHROPIC_API_KEY in your .env file to a real key.\n"
            "       cp .env.example .env && nano .env\n"
        )
        sys.exit(1)

    # ── Mock data (representative of the AAPL FY2025 10-K run) ────────────────
    mock_financials = FinancialSnapshot(
        ticker="AAPL",
        company_name="Apple Inc.",
        sector="Technology",
        industry="Consumer Electronics",
        market_cap=4_498_883_870_720,
        pe_ratio=37.04,
        forward_pe=32.1,
        price_to_book=61.5,
        revenue_ttm=391_035_000_000,
        net_income_ttm=93_736_000_000,
        eps_ttm=6.08,
        dividend_yield=0.0046,
        fifty_two_week_high=260.10,
        fifty_two_week_low=164.08,
        current_price=214.24,
        analyst_target_price=245.83,
        recommendation="buy",
    )

    mock_filing = SECFiling(
        ticker="AAPL",
        cik="0000320193",
        form_type="10-K",
        filed_date=date(2025, 10, 31),
        accession_number="0000320193-25-000079",
        filing_url=(
            "https://www.sec.gov/Archives/edgar/data/320193/"
            "000032019325000079/0000320193-25-000079.txt"
        ),
        document_url=(
            "https://www.sec.gov/Archives/edgar/data/320193/"
            "000032019325000079/aapl-20250927.htm"
        ),
        text_content=(
            "Apple Inc.\n"
            "UNITED STATES SECURITIES AND EXCHANGE COMMISSION\n"
            "Washington, D.C. 20549\n\n"
            "FORM 10-K\n\n"
            "ANNUAL REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934\n"
            "For the fiscal year ended September 27, 2025\n\n"
            "BUSINESS OVERVIEW\n"
            "Apple designs, manufactures, and markets smartphones, personal computers, tablets, "
            "wearables, and accessories. The company also sells a variety of related services. "
            "Net sales increased 4 percent year-over-year to $391.0 billion, driven by Services "
            "growth of 14 percent to a record $96.2 billion. iPhone revenue of $201.0 billion "
            "represents 51 percent of total revenue. The company generated $118.3 billion in "
            "operating cash flow and returned $110.2 billion to shareholders through dividends "
            "and share repurchases. Gross margin expanded to 46.2 percent, the highest in over "
            "a decade, driven by favorable Services mix. The installed base of active devices "
            "reached 2.35 billion units, a new all-time high. International revenue represented "
            "59 percent of total net sales. The company ended the fiscal year with net cash of "
            "$48.2 billion after allocating capital to research and development ($31.4 billion), "
            "capital expenditures ($9.4 billion), and the capital return programme.\n\n"
            "RISK FACTORS\n"
            "The company operates in highly competitive markets. Macroeconomic conditions, "
            "including inflation, interest rate changes, and geopolitical tensions, could "
            "adversely affect consumer demand and supply chain operations. Regulatory risks "
            "include ongoing antitrust investigations in Europe and the United States related "
            "to the App Store, as well as potential changes to data privacy legislation. "
            "The company relies on third-party manufacturing partners, primarily in China, "
            "creating concentration risk. Currency fluctuations and trade policy changes "
            "could affect international revenue and cost of sales."
        ),
    )

    mock_sentiment = SentimentResult(score=0.6243, label="positive", confidence=0.7811)

    # ── Run ───────────────────────────────────────────────────────────────────
    print(f"\nGenerating research brief for AAPL using {_DEFAULT_MODEL}…")
    print("(prompt caching active — second run will be faster)\n")

    generator = BriefGenerator()
    brief = generator.generate(mock_filing, mock_financials, mock_sentiment)

    # ── Print ─────────────────────────────────────────────────────────────────
    section_attrs = [
        ("COMPANY OVERVIEW",    brief.company_overview),
        ("EARNINGS ANALYSIS",   brief.earnings_analysis),
        ("SENTIMENT ASSESSMENT",brief.sentiment_assessment),
        ("BULL CASE",           brief.bull_case),
        ("BEAR CASE",           brief.bear_case),
        ("KEY RISKS",           brief.key_risks),
        ("INVESTMENT OUTLOOK",  brief.investment_outlook),
    ]

    print("=" * 72)
    for title, content in section_attrs:
        print(f"\n## {title}")
        print(content or "[empty — section not found in response]")
    print("\n" + "=" * 72)

    # Token usage summary
    print(
        f"\nToken usage:"
        f"  input={brief.input_tokens}"
        f"  output={brief.output_tokens}"
        f"  cache_read={brief.cache_read_tokens}"
        f"  cache_creation={brief.cache_creation_tokens}"
    )
    print(f"Generated at : {brief.generated_at.isoformat()}")
    print(f"Model        : {brief.model}")
